version: "3.3"
services:
  mango-service-v3:
    build: mango-service-v3
    ports:
      - "3000:3000"
    volumes:
      - ~/.config/solana:/root/.config/solana # mount volume where keys are present, also see PRIVATE_KEY_PATH
    environment:
      - PORT=3000
      - GROUP_NAME=mainnet.1
      - CLUSTER_URL=${CLUSTER_URL} # configure custom RPC node
      - PRIVATE_KEY_PATH=/usr/id.json # configure path to private keypair here
  mango-bowl:
    build: "mango-bowl"
    ports:
      - "8005:8005"
    environment:
      - MB_PORT=8000
      - MB_ENDPOINT=${CLUSTER_URL} # configure custom RPC node
  reverse-proxy:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf/:/etc/nginx/nginx.conf # custom config which unifies mango-service-v3 and mango-bowl