version: "3.3"
services:
  mango-service-v3:
    build: mango-service-v3
    ports:
      - "3000:3000"
    volumes:
      - ~/.config/solana:/root/.config/solana # mount volume where keys are present, also see PRIVATE_KEY_PATH
    environment:
      - PORT=3000
      - GROUP_NAME=mainnet.1
      - meAndThePeeps=5sBpMQgTi7phxqRnErfbwx29vUsbUZoy1MLgY7aXuqeo # separate accounts with commas
      - CLUSTER_URL=https://solana--mainnet--rpc.datahub.figment.io/apikey/995d9d62662252c679a6e673fb31b392 # configure custom RPC node
      - PRIVATE_KEY_PATH=./id.json # configure path to private keypair here
  mango-bowl:
    
    restart: always
    build: "mango-bowl"
    ports:
      - "8005:8005"
    environment:
      - GROUP_NAME=mainnet.1
      - GROUP=mainnet
      - MB_GROUP_NAME=mainnet.1
      - MB_PORT=8005
      - MB_ENDPOINT=https://solana--mainnet--rpc.datahub.figment.io/apikey/995d9d62662252c679a6e673fb31b392 # configure custom RPC node
  mango-client-v3:
    build: mango-client-v3
    restart: always
    ports:
      - "3138:3138"
  py:
    build: py
    network_mode: host
    restart: always
  reverse-proxy:
    build: .
    
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf/:/etc/nginx/nginx.conf # custom config which unifies mango-service-v3 and mango-bowl
  